show con_name;

CREATE USER c##karol IDENTIFIED BY karol;

GRANT
  CREATE SESSION
TO c##karol;

GRANT RESOURCE, CONNECT TO c##karol;

GRANT
  ALTER SESSION,
  CREATE ANY TABLE,
  CREATE CLUSTER,
  CREATE DATABASE LINK,
  CREATE MATERIALIZED VIEW,
  CREATE SYNONYM,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SESSION,
  UNLIMITED TABLESPACE
TO c##karol;

SELECT opg_apis.get_opg_version() FROM DUAL;